# Debian 9 "stretch": host GCC 6.3.0, as in Espressif's toolchain build ("compiled by GNU C 6.3.0")
FROM docker.io/library/debian:stretch
RUN printf 'deb http://archive.debian.org/debian stretch main\ndeb http://archive.debian.org/debian-security stretch/updates main\n' > /etc/apt/sources.list \
 && apt-get -o Acquire::Check-Valid-Until=false update \
 && apt-get install -y --no-install-recommends build-essential autoconf automake bison flex gawk gperf \
    help2man libtool libtool-bin make texinfo git wget curl ca-certificates python3 python3-dev python3-pip \
    python3-setuptools unzip xz-utils bzip2 libncurses5-dev rsync file patch pkg-config ninja-build netbase \
 && rm -rf /var/lib/apt/lists/*
RUN pip3 install meson==0.56.2
