# Build environment for Espressif's crosstool-NG (like their Linux x86_64 build)
FROM docker.io/library/ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential autoconf automake bison flex gawk gperf help2man libtool libtool-bin make \
    meson ninja-build texinfo git wget curl ca-certificates python3 python3-dev unzip xz-utils \
    bzip2 libncurses-dev rsync file patch pkg-config zstd libzstd-dev netbase \
 && rm -rf /var/lib/apt/lists/*
